### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [GiorgioBertolotti/PWSWatcher#26]
Hi Giorgio, this looks like a giorgious app (forgive me the pun :wink:)! And you write it's open source, which is great (plus it comes without any trackers, which makes it even greater)! Could you let us know what Open Source license you chose? Thanks!

**Comment by GiorgioBertolotti** [comment]
Hello @IzzySoft, hope you're doing fine!
I've added just now the LICENSE file (MIT) in the repository root directory, thanks a lot for reporting it!

PS: the pun was nice 😂

**Comment by IzzySoft** [comment]
Thanks Giorgio! And I was hoping you'd enjoy the pun :smile: As I hope you'll [enjoy this](https://apt.izzysoft.de/fdroid/index/apk/com.zem.pwswatcher) (license will show up with the next sync tomorrow). Be welcome to point there from e.g. your Readme. People can use the [F-Droid](https://f-droid.org/) app to install/update from there. New versions usually show up within 24h of your attaching the APK to a new release (an updater script takes care for that). Don't hesitate asking if you've got any questions on this, or want the description updated/changed.

**Comment by GiorgioBertolotti** [comment]
@IzzySoft Sounds great, thanks!
I'll be happy to add the link to the README :)

**Comment by IzzySoft** [comment]
Cool! If you need a badge, look what [just popped up](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it):

[<img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png" width="200">](https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png)
