### ISSUE TITLE
Add Air Quality

### ISSUE THREAD

**Issue by dshanske** [GiorgioBertolotti/PWSWatcher#38]
Add ability to add air quality to view.

**Comment by GiorgioBertolotti** [comment]
Hello David and sorry for the late response.

I made a quick search for Cumulus MX's realtime.txt and Weather Display's clientraw.txt but I didn't find any value representing the Air Quality Index or any of the values used to calculate it.
What could be done is to add a location picker and use an external API (like this: https://aqicn.org/api/) to fetch and display the informations about the Air Quality.

What do you think about it? Do you have any better idea?

Thanks

**Comment by dshanske** [comment]
I apologize...I have pm1, pm2.5, and pm10 as part of my data stream. I was looking for a way to display them in the UI

**Comment by dshanske** [comment]
The issue being you only allow two bits of custom data according to the XML customization guide and this has no icon

**Comment by GiorgioBertolotti** [comment]
Okay so your idea is to allow to customize the data shown in home using the variable names shown in the PWS detail page, right?

**Comment by dshanske** [comment]
Yes, basically

**Comment by dshanske** [comment]
I am a weewx user, and they added additional parameters during the last expansion of their schema.

**Comment by GiorgioBertolotti** [comment]
Cool, okay I'll add it as soon as possible, unfortunately I'm a little bit busy at the moment...

**Comment by dshanske** [comment]
@GiorgioBertolotti I can understand. Me as well.

**Comment by GiorgioBertolotti** [comment]
@dshanske I'm releasing a new version, it will add the possibility to add custom variables (from Detail Page) to the home.
